### PR TITLE
Updates for BloodRelay

### PR DESCRIPTION
**Pull request by eric-hemasystems**
Using this to help with implementing BloodRelay. Since it is a newer app it was already on the 2.x series of the JSON gem.

Technically I could downgrade to 1.8.1 but then I would get warnings due to the Ruby 2.4 integer unification. Since this version was pinned with the initial commit I assume that pin is out-of-date and using a newer version will work.

Ran the tests and they still all pass.

Went ahead and bumped the Gemfile.lock (`bundle update`). Generally I don't think Gemfile.lock files are checked into repos for libraries since the gemspec is all that is used.

### CODE REVIEW

**Comment by moliver-hemasystems** [comment]
Do we need to adjust the version this for this change?  Or are we planning on whatever future deploys to re-build the gemset for the apps?  Since we're changing the dependencies, will there be any concerns with conflict for the other apps if they update on-deploy?  Mostly, I don't want to risk BH not releasing to production tomorrow night when we do the 6.3 release because of some unknown issue.

**Comment by eric-hemasystems** [comment]
I just removed the pinning to json 1.8.1 but that version is still compatible. So unless you `bundle update json` on a specific app it should impact any other app. But feel free to delay on merging this until after the release tomorrow if you want. I've just used the `github` and `branch` tag to use my fork in the BloodRelay gemfile for now so its not blocking me.

**Comment by eric-hemasystems** [comment]
I wasn't going to bump the version on the gem yet as integrating this into BloodRelay may make other PRs. Figure once it is integrated we can bump the version of this gem and do a release of it.

**Comment by moliver-hemasystems** [comment]
I didn't realize BH had 1.8.3 specified in its gemfile, so it's not a problem now.  I was just concerned that if we removed the upper limit from here, that would cause Heroku to fetch the latest on the next deploy, since the deploy would rebuild the gemset for the dynos it spins up; assuming BH didn't have any version specified.  Since it does, it's got a safety net, so I'm ok now.

It wouldn't matter for the PR merge though, just the publish to rubygems.  I guess I'm version-change happy since we're the only people who use this gem.  All's good for me now.

**Comment by eric-hemasystems** [comment]
Even if BH didn't pin to 1.8.3 it still won't bump due to the `Gemfile.lock` locking it to 1.8.3. Until you run `bundler update` and commit the updated `Gemfile.lock` in BH the versions will stay the same no matter what upstream gems use.

The only exception to this is if someone yanks a gem (removes an old version). I've had deploys break from that before. :(

**Comment by moliver-hemasystems** [comment]
Well, then I'm double ok with it then.  For some reason I got panic on the changes with no versioning a day before a software release.  I'm MUCH happier that it was all unfounded.

**Pull request merged**
